<a href="https://colab.research.google.com/github/25wh1a05ak-lilly/NASSCOM/blob/main/WEEK%202/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")


# =========================================================
# TASK 1: Basic Pandas Functions and Converting Arrays
# =========================================================
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2 Create a 3x4 NumPy array with random integers from 1 to 100
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

# 1.3 Convert NumPy array into DataFrame
df1_3 = pd.DataFrame(
    np_array1_2,
    columns=['A', 'B', 'C', 'D']
)

print("\ns1_1:")
print(s1_1)

print("\nnp_array1_2:")
print(np_array1_2)

print("\ndf1_3:")
print(df1_3)


# =========================================================
# TASK 2: Synthetic Data Generation for Practice
# =========================================================
print("\n--- Task 2: Synthetic Data Generation for Practice ---")

# Set seed so results are reproducible
np.random.seed(42)

# Create 100 dates
dates = pd.date_range(start='2023-01-01', periods=100, freq='D')

# Create DataFrame
df_sales = pd.DataFrame({
    'Date': dates,
    'Region': np.random.choice(
        ['East', 'West', 'North', 'South'],
        size=100
    ),
    'Product': np.random.choice(
        ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
        size=100
    ),
    'Sales': np.random.randint(100, 1001, size=100),
    'Quantity': np.random.randint(1, 11, size=100)
})

# Introduce 5 random NaN values in Sales
sales_nan_indices = np.random.choice(
    df_sales.index,
    size=5,
    replace=False
)

df_sales.loc[sales_nan_indices, 'Sales'] = np.nan

# Introduce 3 random NaN values in Quantity
quantity_nan_indices = np.random.choice(
    df_sales.index,
    size=3,
    replace=False
)

df_sales.loc[quantity_nan_indices, 'Quantity'] = np.nan

print("\ndf_sales:")
print(df_sales)

print("\nShape of df_sales:")
print(df_sales.shape)


# =========================================================
# TASK 3: Indexing and Slicing in DataFrames
# =========================================================
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

# 3.1 Select Region and Sales columns
df3_1 = df_sales[['Region', 'Sales']]

# 3.2 Select rows where Product is Laptop
df3_2 = df_sales[df_sales['Product'] == 'Laptop']

# 3.3 Region is East AND Sales > 500
df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]

# 3.4 Select Sales value for first Monitor
monitor_rows = df_sales[df_sales['Product'] == 'Monitor']

if not monitor_rows.empty:
    first_monitor_index = monitor_rows.index[0]

    # Using .loc
    val3_4_loc = df_sales.loc[first_monitor_index, 'Sales']

    # Using .iloc
    position = df_sales.index.get_loc(first_monitor_index)
    val3_4_iloc = df_sales.iloc[position]['Sales']

    # Store the value as requested
    val3_4 = val3_4_loc
else:
    val3_4 = np.nan

print("\ndf3_1:")
print(df3_1)

print("\ndf3_2:")
print(df3_2)

print("\ndf3_3:")
print(df3_3)

print("\nval3_4 using .loc:", val3_4_loc if not monitor_rows.empty else np.nan)
print("val3_4 using .iloc:", val3_4_iloc if not monitor_rows.empty else np.nan)


# =========================================================
# TASK 4: Data Cleaning
# =========================================================
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

# 4.1 Count missing values in each column
missing_counts4_1 = df_sales.isna().sum()

# 4.2 Fill missing Sales with mean Sales
df4_2_filled = df_sales.copy()

sales_mean = df4_2_filled['Sales'].mean()

df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(sales_mean)

# 4.3 Drop rows containing any missing values
df4_3_dropped = df_sales.dropna()

print("\nmissing_counts4_1:")
print(missing_counts4_1)

print("\ndf4_2_filled:")
print(df4_2_filled)

print("\ndf4_3_dropped:")
print(df4_3_dropped)


# =========================================================
# TASK 5: Data Manipulation
# =========================================================
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

# 5.1 Create Total_Revenue
df_sales['Total_Revenue'] = (
    df_sales['Sales'] * df_sales['Quantity']
)

# 5.2 Sort by Date ascending and Sales descending
df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)

# 5.3 Group by Region and calculate sum of Sales and Quantity
df5_3_grouped_region = (
    df_sales
    .groupby('Region')[['Sales', 'Quantity']]
    .sum()
)

# 5.4 Group by Product and calculate average Sales
df5_4_grouped_product = (
    df_sales
    .groupby('Product')['Sales']
    .mean()
)

print("\ndf_sales with Total_Revenue:")
print(df_sales)

print("\ndf5_2_sorted:")
print(df5_2_sorted)

print("\ndf5_3_grouped_region:")
print(df5_3_grouped_region)

print("\ndf5_4_grouped_product:")
print(df5_4_grouped_product)




--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---

s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64

np_array1_2:
[[55 39 97  5]
 [23 85 18 96]
 [ 3 21 71  4]]

df1_3:
    A   B   C   D
0  55  39  97   5
1  23  85  18  96
2   3  21  71   4

--- Task 2: Synthetic Data Generation for Practice ---

df_sales:
         Date Region   Product  Sales  Quantity
0  2023-01-01  North  Keyboard  674.0       7.0
1  2023-01-02  South     Mouse  963.0       4.0
2  2023-01-03   East     Mouse    NaN       7.0
3  2023-01-04  North   Monitor  340.0       8.0
4  2023-01-05  North     Mouse  663.0       1.0
..        ...    ...       ...    ...       ...
95 2023-04-06   West     Mouse  152.0       6.0
96 2023-04-07   West     Mouse  783.0       8.0
97 2023-04-08  South   Monitor  829.0       2.0
98 2023-04-09   West    Laptop  771.0       5.